# A Docker Compose file for running the Multimodal Participant State Model web
# service as a standalone container.

version: '3'
services:
  uaz_mm_encoder:
    image: uaz_mm_encoder:latest
    container_name: uaz_mm_encoder
    build: .
    ports:
      # Change the line below if you want to use a different port mapping. The
      # format is "host_port:container_port".
      - "8000:8000"
    entrypoint: uvicorn mmc_server:app --host 0.0.0.0
