from python:3.7
run pip install\
    six\
    websockets\
    numpy\
    paho-mqtt\
    google-cloud-speech
copy * /
expose 8888
entrypoint ["./tomcat_asr_agent", "websockets", "--use_mqtt", "--ws_host", "0.0.0.0", "--ws_port", "8888", "--mqtt_host", "host.docker.internal"]
