#!/usr/bin/env python

"""Agent that uses the Google Cloud streaming speech recognition API to perform
real-time ASR.

Author: Adarsh Pyarelal (adarsh@arizona.edu)

This code is adapted from the example provided by Google at
https://github.com/googleapis/python-speech/blob/master/samples/microphone/transcribe_streaming_mic.py

Example usage:
    ./asr_agent
"""

from __future__ import division

import re
import sys
import datetime
from dataclasses import dataclass, asdict, field, InitVar
import json

import pyaudio

from six.moves import queue
from google.cloud import speech
from paho.mqtt.client import Client as MQTTClient


class MicrophoneStream(object):
    """Opens a recording stream as a generator yielding the audio chunks."""

    def __init__(self, rate, chunk):
        self._rate = rate
        self._chunk = chunk

        # Create a thread-safe buffer of audio data
        self._buff = queue.Queue()
        self.closed = True

    def __enter__(self):
        self._audio_interface = pyaudio.PyAudio()
        self._audio_stream = self._audio_interface.open(
            format=pyaudio.paInt16,
            # The API currently only supports 1-channel (mono) audio
            # https://goo.gl/z757pE
            channels=1,
            rate=self._rate,
            input=True,
            frames_per_buffer=self._chunk,
            # Run the audio stream asynchronously to fill the buffer object.
            # This is necessary so that the input device's buffer doesn't
            # overflow while the calling thread makes network requests, etc.
            stream_callback=self._fill_buffer,
        )

        self.closed = False

        return self

    def __exit__(self, type, value, traceback):
        self._audio_stream.stop_stream()
        self._audio_stream.close()
        self.closed = True
        # Signal the generator to terminate so that the client's
        # streaming_recognize method will not block the process termination.
        self._buff.put(None)
        self._audio_interface.terminate()

    def _fill_buffer(self, in_data, frame_count, time_info, status_flags):
        """Continuously collect data from the audio stream, into the buffer."""
        print(in_data, frame_count, time_info, status_flags)
        self._buff.put(in_data)
        return None, pyaudio.paContinue

    def generator(self):
        while not self.closed:
            # Use a blocking get() to ensure there's at least one chunk of
            # data, and stop iteration if the chunk is None, indicating the
            # end of the audio stream.
            chunk = self._buff.get()
            if chunk is None:
                return
            data = [chunk]

            # Now consume whatever other data's still buffered.
            while True:
                try:
                    chunk = self._buff.get(block=False)
                    if chunk is None:
                        return
                    data.append(chunk)
                except queue.Empty:
                    break

            yield b"".join(data)


@dataclass(frozen=True)
class TA3Header(object):
    timestamp: str
    message_type: str = "observation"
    version: str = "0.1"


@dataclass(frozen=True)
class TA3Msg(object):
    timestamp: str
    experiment_id: str = None
    trial_id: str = None
    version: str = "0.1"
    source: str = "tomcat_asr_agent"
    sub_type: str = "asr"

@dataclass(frozen=True)
class TA3Data(object):
    text: str
    asr_system: str

@dataclass
class TA3Message(object):
    """Class to represent a TA3 testbed message."""
    data: TA3Data
    header: TA3Header = field(init=False)
    msg: TA3Msg = field(init=False)

    def __post_init__(self):
        timestamp: str = datetime.datetime.utcnow().isoformat() + "Z"
        self.header = TA3Header(timestamp)
        self.msg = TA3Msg(timestamp)

def listen_print_loop(responses):
    """Iterates through server responses and prints them.

    The responses passed is a generator that will block until a response
    is provided by the server.

    Each response may contain multiple results, and each result may contain
    multiple alternatives; for details, see https://goo.gl/tjCPAU.  Here we
    print only the transcription for the top alternative of the top result.

    In this case, responses are provided for interim results as well. If the
    response is an interim one, print a line feed at the end of it, to allow
    the next result to overwrite it, until the response is a final one. For the
    final one, print a newline to preserve the finalized transcription.
    """
    for response in responses:
        if not response.results:
            continue

        # The `results` list is consecutive. For streaming, we only care about
        # the first result being considered, since once it's `is_final`, it
        # moves on to considering the next utterance.
        result = response.results[0]
        if not result.alternatives:
            continue

        # Display the transcription of the top alternative.
        transcript = result.alternatives[0].transcript

        if result.is_final:
            ta3_data = TA3Data(transcript, "Google")
            print(json.dumps(asdict(TA3Message(ta3_data))))

            # We call sys.stdout.flush() to make this program work with piping,
            # for example, through the jq program.
            sys.stdout.flush()
            # mqtt_client.publish("agents/asr_agent", transcript)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="ToMCAT ASR Agent")

    # Audio recording parameters
    rate = 16000
    chunk = int(rate / 10)  # 100ms

    # See http://g.co/cloud/speech/docs/languages
    # for a list of supported languages.
    language_code = "en-US"  # a BCP-47 language tag

    speech_client = speech.SpeechClient()
    config = speech.RecognitionConfig(
        encoding=speech.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=rate,
        language_code=language_code,
    )

    streaming_config = speech.StreamingRecognitionConfig(
        config=config, interim_results=True
    )

    # Set up the Paho MQTT client.
    # mqtt_client = MQTTClient()
    # mqtt_client.connect("localhost", 1883, 60)

    with MicrophoneStream(rate, chunk) as stream:
        audio_generator = stream.generator()
        requests = (
            speech.StreamingRecognizeRequest(audio_content=content)
            for content in audio_generator
        )

        responses = speech_client.streaming_recognize(
            streaming_config, requests
        )

        # Now, put the transcription responses to use.
        listen_print_loop(responses)
